from django.urls import path

from reports.views import (
    AnalyticsPDFExportView,
    AuditLogListAPIView,
    CompleteOHCIntakePageView,
    DashboardView,
    DepartmentHealthStatsAPIView,
    DepartmentHealthStatsExcelExportView,
    DepartmentHealthStatsPageView,
    DiagnosisEntryPageView,
    DiseaseTrendsAPIView,
    DiseaseTrendsPageView,
    EmployeeHealthHistoryAPIView,
    EmployeeHealthHistoryExcelExportView,
    EmployeeHealthHistoryPageView,
    HospitalSelectionPageView,
    NotificationListAPIView,
    OHCVisitFormPageView,
    PaymentPageView,
    PublicHowItWorksView,
    PublicLandingView,
    ReferralPageView,
    ReportsPageView,
    RunAutoAlertsAPIView,
)

urlpatterns = [
    path("", PublicLandingView.as_view(), name="public-home"),
    path("how-it-works/", PublicHowItWorksView.as_view(), name="how-it-works"),
    path("dashboard/", DashboardView.as_view(), name="dashboard-home"),
    path("ohc/visit-form/", OHCVisitFormPageView.as_view(), name="ohc-visit-form"),
    path("ohc/diagnosis-entry/", DiagnosisEntryPageView.as_view(), name="diagnosis-entry"),
    path("ohc/complete-intake/", CompleteOHCIntakePageView.as_view(), name="complete-ohc-intake-page"),
    path("ahc/referrals/", ReferralPageView.as_view(), name="referral-page"),
    path("ahc/hospital-selection/", HospitalSelectionPageView.as_view(), name="hospital-selection"),
    path("reports/medical/", ReportsPageView.as_view(), name="reports-page"),
    path("reports/employee-history/", EmployeeHealthHistoryPageView.as_view(), name="employee-health-history-page"),
    path("reports/disease-trends/", DiseaseTrendsPageView.as_view(), name="disease-trends-page"),
    path("reports/department-stats/", DepartmentHealthStatsPageView.as_view(), name="department-health-stats-page"),
    path("payments/", PaymentPageView.as_view(), name="payment-page"),
    path("api/reports/employee-health-history/", EmployeeHealthHistoryAPIView.as_view(), name="employee-health-history-api"),
    path("api/reports/disease-trends/", DiseaseTrendsAPIView.as_view(), name="disease-trends-api"),
    path("api/reports/department-health-stats/", DepartmentHealthStatsAPIView.as_view(), name="department-health-stats-api"),
    path("api/reports/notifications/", NotificationListAPIView.as_view(), name="notifications-api"),
    path("api/reports/audit-logs/", AuditLogListAPIView.as_view(), name="audit-logs-api"),
    path("api/reports/run-auto-alerts/", RunAutoAlertsAPIView.as_view(), name="run-auto-alerts-api"),
    path("exports/employee-health-history.csv", EmployeeHealthHistoryExcelExportView.as_view(), name="employee-history-export"),
    path("exports/department-health-stats.csv", DepartmentHealthStatsExcelExportView.as_view(), name="department-stats-export"),
    path("exports/analytics-summary.pdf", AnalyticsPDFExportView.as_view(), name="analytics-pdf-export"),
]
