# Generated by Django 5.2.6 on 2026-05-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('NURSE', 'Nurse'), ('EHS', 'EHS Team'), ('HR', 'HR'), ('KAM', 'KAM'), ('DOCTOR', 'On Site Doctor'), ('EMPLOYEE', 'Employee')], max_length=20),
        ),
    ]
