# Generated by Django 5.2.6 on 2026-05-16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        # Remove uuid from BaseModel-inheriting models
        migrations.RemoveField(
            model_name='employeeprofile',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='uuid',
        ),
    ]