# Generated by Django 5.2.6 on 2026-05-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_remove_uuid_from_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('ADMIN', 'Admin'),
                    ('NURSE', 'Nurse'),
                    ('EHS', 'EHS Team'),
                    ('HR', 'HR'),
                    ('KAM', 'KAM'),
                    ('DOCTOR', 'On Site Doctor'),
                    ('EMPLOYEE', 'Employee'),
                    ('PHARMACIST', 'Pharmacist'),
                    ('MANAGEMENT', 'Management'),
                ],
            ),
        ),
    ]
