[pytest]
DJANGO_SETTINGS_MODULE = myproject.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test* *Tests
python_functions = test_*
addopts =
    --cov=ohc
    --cov=accounts
    --cov-report=term-missing
    --cov-report=html:docs/testing/coverage-report
    --verbose