# Generated by Django 5.2.6 on 2026-05-01 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ohc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('hospital_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=15)),
                ('hospital_type', models.CharField(blank=True, max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('accreditation_number', models.CharField(blank=True, max_length=120)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('supports_cashless', models.BooleanField(default=False)),
                ('is_available_for_video', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_reason', models.TextField()),
                ('specialist_department', models.CharField(blank=True, max_length=150)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=20)),
                ('referral_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_HOSPITAL_SELECTION', 'Pending Hospital Selection'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('IN_TREATMENT', 'In Treatment'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_HOSPITAL_SELECTION', max_length=40)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('external_case_id', models.CharField(blank=True, max_length=120)),
                ('treatment_summary', models.TextField(blank=True)),
                ('closure_notes', models.TextField(blank=True)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='ohc.diagnosis')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='accounts.employeeprofile')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='ahc.hospital')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_created', to='accounts.doctorprofile')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='ohc.ohcvisit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('LAB', 'Lab Report'), ('IMAGING', 'Imaging'), ('DISCHARGE', 'Discharge Summary'), ('FITNESS', 'Fitness Certificate'), ('PRESCRIPTION', 'Prescription'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('report_file', models.FileField(upload_to='medical_reports/')),
                ('report_date', models.DateField()),
                ('is_confidential', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_reports', to='accounts.employeeprofile')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='ahc.hospital')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_medical_reports', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='ohc.ohcvisit')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='ahc.referral')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
