# Generated by Django 5.2.6 on 2026-05-16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ahc', '0001_initial'),
    ]

    operations = [
        # Remove uuid from BaseModel-inheriting models
        migrations.RemoveField(
            model_name='hospital',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='uuid',
        ),
    ]