# Generated by Django 5.2.6 on 2026-05-16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        # Remove uuid from BaseModel-inheriting models
        migrations.RemoveField(
            model_name='auditlog',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='uuid',
        ),
        # Note: target_object_uuid and related_object_uuid fields remain
        # as they reference object IDs, not self-uuid
    ]