# Generated by Django 5.2.6 on 2026-05-01 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis_code', models.CharField(blank=True, max_length=50)),
                ('diagnosis_name', models.CharField(max_length=255)),
                ('diagnosis_notes', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SERIOUS', 'Serious'), ('CRITICAL', 'Critical')], default='MILD', max_length=15)),
                ('condition_status', models.CharField(choices=[('ACTIVE', 'Active'), ('STABLE', 'Stable'), ('RESOLVED', 'Resolved'), ('CHRONIC', 'Chronic')], default='ACTIVE', max_length=15)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_referral_required', models.BooleanField(default=False)),
                ('fitness_decision', models.CharField(choices=[('FIT', 'Fit'), ('FIT_WITH_RESTRICTION', 'Fit With Restriction'), ('TEMPORARY_UNFIT', 'Temporary Unfit'), ('UNFIT', 'Unfit')], default='FIT', max_length=30)),
                ('work_restrictions', models.TextField(blank=True)),
                ('advised_rest_days', models.PositiveIntegerField(default=0)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('diagnosed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses_made', to='accounts.doctorprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OHCVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_type', models.CharField(choices=[('WALK_IN', 'Walk In'), ('PERIODIC', 'Periodic Checkup'), ('PRE_EMPLOYMENT', 'Pre-employment'), ('FOLLOW_UP', 'Follow Up'), ('EMERGENCY', 'Emergency')], default='WALK_IN', max_length=30)),
                ('visit_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('REFERRED', 'Referred'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('triage_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('visit_date', models.DateTimeField()),
                ('chief_complaint', models.CharField(max_length=255)),
                ('symptoms', models.TextField(blank=True)),
                ('vitals', models.JSONField(blank=True, default=dict)),
                ('preliminary_notes', models.TextField(blank=True)),
                ('requires_referral', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('consulted_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ohc_visits', to='accounts.doctorprofile')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ohc_visits', to='accounts.employeeprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_name', models.CharField(max_length=255)),
                ('test_type', models.CharField(max_length=120)),
                ('laboratory_name', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT')], default='ROUTINE', max_length=10)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('result_summary', models.TextField(blank=True)),
                ('result_value', models.CharField(blank=True, max_length=120)),
                ('result_unit', models.CharField(blank=True, max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_tests', to='ohc.diagnosis')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_tests_requested', to='accounts.doctorprofile')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_tests', to='ohc.ohcvisit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='ohc.ohcvisit'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField()),
                ('route', models.CharField(blank=True, max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped')], default='ACTIVE', max_length=20)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='ohc.diagnosis')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_written', to='accounts.doctorprofile')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='ohc.ohcvisit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
