# Generated by Django 5.2.6 on 2026-05-16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ohc', '0001_initial'),
    ]

    operations = [
        # Remove uuid from BaseModel-inheriting models
        migrations.RemoveField(
            model_name='diagnosis',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='ohcvisit',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='uuid',
        ),
    ]