# Generated by Django 5.2.6 on 2026-05-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ohc', '0002_remove_uuid_from_ohc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ohcvisit',
            name='visit_status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('OPEN', 'Open'),
                    ('IN_PROGRESS', 'In Progress'),
                    ('REFERRED', 'Referred'),
                    ('CLOSED', 'Closed'),
                    ('CANCELLED', 'Cancelled'),
                    ('COMPLETED', 'Completed'),
                ],
            ),
        ),
    ]
