# Generated by Django 5.2.6 on 2026-05-21 00:00
# No-op migration - closed_at already exists in initial migration

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ohc', '0007_add_completed_status'),
    ]

    operations = []
