# Generated by Django 5.2.6 on 2026-05-21 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('ohc', '0008_add_closed_at_to_ohcvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicine_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('initial_stock', models.PositiveIntegerField(default=0)),
                ('used_quantity', models.PositiveIntegerField(default=0)),
                ('supplier', models.CharField(max_length=255, blank=True)),
                ('batch_number', models.CharField(max_length=100, blank=True)),
                ('expiry_date', models.DateField(null=True, blank=True)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('last_dispensed_at', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='medicinestock',
            index=models.Index(fields=['medicine_id'], name='med_medicine_id_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinestock',
            index=models.Index(fields=['name'], name='med_name_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinestock',
            index=models.Index(fields=['expiry_date'], name='med_expiry_date_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinestock',
            index=models.Index(fields=['reorder_level', 'stock_quantity'], name='med_reorder_stock_idx'),
        ),
    ]
