# Generated by Django 5.2.6 on 2026-05-21 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('ohc', '0009_create_medicinestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDispense',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicine', models.ForeignKey(
                    'ohc.MedicineStock',
                    on_delete=models.PROTECT,
                    related_name='dispense_records',
                )),
                ('visit', models.ForeignKey(
                    'ohc.OHCVisit',
                    on_delete=models.CASCADE,
                    related_name='medicine_dispenses',
                )),
                ('prescription', models.ForeignKey(
                    'ohc.Prescription',
                    on_delete=models.SET_NULL,
                    null=True,
                    blank=True,
                    related_name='dispenses',
                )),
                ('dispensed_by', models.ForeignKey(
                    'accounts.User',
                    on_delete=models.PROTECT,
                    related_name='dispenses_made',
                )),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('issue_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(
                    max_length=20,
                    choices=[
                        ('PENDING', 'Pending'),
                        ('DISPENSED', 'Dispensed'),
                        ('CANCELLED', 'Cancelled'),
                    ],
                    default='DISPENSED',
                )),
            ],
        ),
    ]
