# Generated by Django 5.2.6 on 2026-05-21 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('ohc', '0010_create_medicinedispense'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitStatusLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit', models.ForeignKey(
                    'ohc.OHCVisit',
                    on_delete=models.CASCADE,
                    related_name='status_logs',
                )),
                ('from_status', models.CharField(max_length=20, blank=True)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_by', models.ForeignKey(
                    'accounts.User',
                    on_delete=models.PROTECT,
                    related_name='status_changes_made',
                )),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
