# Generated by Django 5.2.6 on 2026-05-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohc', '0011_create_visitstatuslog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicinestock',
            new_name='ohc_medicin_medicin_442c49_idx',
            old_name='med_medicine_id_idx',
        ),
        migrations.RenameIndex(
            model_name='medicinestock',
            new_name='ohc_medicin_name_363f56_idx',
            old_name='med_name_idx',
        ),
        migrations.RenameIndex(
            model_name='medicinestock',
            new_name='ohc_medicin_expiry__76091b_idx',
            old_name='med_expiry_date_idx',
        ),
        migrations.RenameIndex(
            model_name='medicinestock',
            new_name='ohc_medicin_reorder_fda307_idx',
            old_name='med_reorder_stock_idx',
        ),
        migrations.AlterField(
            model_name='medicinedispense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicinedispense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicinedispense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='unit',
            field=models.CharField(choices=[('TABLETS', 'Tablets'), ('CAPSULES', 'Capsules'), ('SYRUP', 'Syrup (ml)'), ('INJECTION', 'Injection (ml)'), ('DROPS', 'Drops (ml)'), ('OINTMENT', 'Ointment (g)'), ('CREAM', 'Cream (g)'), ('PATCH', 'Patch'), ('INHALER', 'Inhaler (puffs)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ohcvisit',
            name='visit_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('REFERRED', 'Referred'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitstatuslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visitstatuslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visitstatuslog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
