# Generated by Django 5.2.6 on 2026-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohc', '0012_rename_med_medicine_id_idx_ohc_medicin_medicin_442c49_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohcvisit',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ohcvisit',
            name='patient_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ohcvisit',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ohcvisit',
            name='patient_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ohcvisit',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ohcvisit',
            name='chief_complaint',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
