# Generated by Django 5.2.6 on 2026-05-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohc', '0014_fix_examination_notes_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='examination_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
