# Generated by Django 5.2.6 on 2026-05-30 05:35

from django.db import migrations, models


def add_examination_notes_if_missing(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info(ohc_diagnosis)")
        existing_columns = {row[1] for row in cursor.fetchall()}

    if "examination_notes" in existing_columns:
        return

    schema_editor.execute(
        "ALTER TABLE ohc_diagnosis ADD COLUMN examination_notes TEXT NULL"
    )


def remove_examination_notes_if_present(apps, schema_editor):
    # SQLite does not support dropping a column directly, and this migration
    # exists to repair drifted local databases rather than to support rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ohc", "0014_fix_examination_notes_nullable"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_examination_notes_if_missing,
                    remove_examination_notes_if_present,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="diagnosis",
                    name="examination_notes",
                    field=models.TextField(blank=True, null=True),
                ),
            ],
        ),
    ]
